# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CounterCallAPI(object):
    def setupUi(self, CounterCallAPI):
        CounterCallAPI.setObjectName("CounterCallAPI")
        CounterCallAPI.resize(609, 673)
        self.output_info = QtWidgets.QTextBrowser(CounterCallAPI)
        self.output_info.setGeometry(QtCore.QRect(9, 133, 591, 531))
        self.output_info.setObjectName("output_info")
        self.found_dialouts_2 = QtWidgets.QGroupBox(CounterCallAPI)
        self.found_dialouts_2.setGeometry(QtCore.QRect(9, 9, 591, 56))
        self.found_dialouts_2.setObjectName("found_dialouts_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.found_dialouts_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.found_dialouts_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.token_enter = QtWidgets.QLineEdit(self.found_dialouts_2)
        self.token_enter.setObjectName("token_enter")
        self.horizontalLayout.addWidget(self.token_enter)
        self.found_dialouts = QtWidgets.QPushButton(self.found_dialouts_2)
        self.found_dialouts.setObjectName("found_dialouts")
        self.horizontalLayout.addWidget(self.found_dialouts)
        self.get_info_dialouts = QtWidgets.QGroupBox(CounterCallAPI)
        self.get_info_dialouts.setGeometry(QtCore.QRect(9, 71, 591, 56))
        self.get_info_dialouts.setObjectName("get_info_dialouts")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.get_info_dialouts)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.get_info_dialouts)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dialout = QtWidgets.QLineEdit(self.get_info_dialouts)
        self.dialout.setObjectName("dialout")
        self.horizontalLayout_2.addWidget(self.dialout)
        self.get_info_dialout = QtWidgets.QPushButton(self.get_info_dialouts)
        self.get_info_dialout.setObjectName("get_info_dialout")
        self.horizontalLayout_2.addWidget(self.get_info_dialout)

        self.retranslateUi(CounterCallAPI)
        QtCore.QMetaObject.connectSlotsByName(CounterCallAPI)

    def retranslateUi(self, CounterCallAPI):
        _translate = QtCore.QCoreApplication.translate
        CounterCallAPI.setWindowTitle(_translate("CounterCallAPI", "Counter CallAPI number and dialouts"))
        self.found_dialouts_2.setTitle(_translate("CounterCallAPI", "Найти Автообзвоны"))
        self.label.setText(_translate("CounterCallAPI", "Введите token CallAPI:"))
        self.found_dialouts.setText(_translate("CounterCallAPI", "Поиск"))
        self.get_info_dialouts.setTitle(_translate("CounterCallAPI", "Получить информацию об автообзвонах"))
        self.label_2.setText(_translate("CounterCallAPI", "Введите номер автообзвона:"))
        self.get_info_dialout.setText(_translate("CounterCallAPI", "Получить информацию"))
